### ISSUE TITLE
About MOSI datasets.

### ISSUE THREAD

**Issue by Vvvvvvsysy** [tjdevWorks/TEASEL#2]
Nice work for you! but I have some question about the dataset. The datasets you use is raw data for MOSI? and i can't reproduce because i don't know which data to use. or can you share the MOSI datasets you use? Thanks!

**Comment by tjdevWorks** [comment]
I used the CMU_MOSI.zip file available here http://immortal.multicomp.cs.cmu.edu/raw_datasets/.
Let me know if you have any other questions! Happy to help!

**Comment by Vvvvvvsysy** [comment]
And I want to reproduce your work, but when I use a 3090 with 25GB memory, and it still report error CUDA out of memory. So how can I reproduce this work? Use other GPU? Or any other solution?
